docs(van121): 更正 creativeNoClip true 的含义
hit-mc/wiki.hitmc.cc pull request #4
Opened 2024-12-28 15:13 UTC by IcyDesert

如题

2024-12-30 15:06 UTC, Cherrling commented
有具体的 carpet wiki 链接吗

2024-12-30 16:48 UTC, inclyc reviewed
我觉得GPT说的挺清楚的，为什么说“更正”？

2024-12-30 16:58 UTC, Cherrling requested changes
不建议删除原有内容，可以一起保留。而且单一句话描述有点简略了

2024-12-31 05:44 UTC, IcyDesert commented
> 我觉得GPT说的挺清楚的，为什么说“更正”？

GPT 强调的是允许穿墙，但是我觉得这个功能更好的概括应该是 不检测碰撞箱，穿墙只是一个表现，其他的行为还包括不会和矿车等实体碰撞、不会吸取掉落物、不触发绊线钩等等。这些我都在单人档测试过。
另外 GPT 所说的服务端配置的那两项确实不应该删掉，因为我没在服务器测试这些。

2024-12-31 05:45 UTC, IcyDesert commented
> 有具体的 carpet wiki 链接吗 主要涉及是否要去掉原有内容

https://github.com/gnembon/fabric-carpet/blob/d9c7334400ecd75f307806e312a2e64a1cc42302/src/main/resources/assets/carpet/lang/zh_cn.json#L220
这是 carpet 的官方...文档？

2024-12-31 06:52 UTC, Cherrling approved these changes

2024-12-31 07:00 UTC, merged

2024-12-31 07:00 UTC, Cherrling commented
merged